### ISSUE TITLE
[Week2] 2주차 과제

### ISSUE THREAD

**Issue by mnbvcxzyj** [AND-SOPT-iOS/KimYeji#3]
## ⚠️ Issue 
- **앱스토어 - 토스앱 상세 페이지 구현**

## ✅ To-do

- [x] 스크롤로 리뷰 작성 버튼까지 구현 
- [x] 컴포넌트 배치 위주 구현 
- [x] 버전기록 페이지 이동 
- [x] 미리보기 이미지 하나 나오도록 구현 
- [x] 평가 및 리뷰 모두 보기 클릭 시 모두 보기 페이지로 이동만 하도록 연결

## ➕ 추가 구현 선택사항 
- [x] 앱 설명의 더보기를 눌렀을 때, 추가 내용이 보여지도록 구현
- [ ] 리뷰 작성 시 나오는 리뷰 작성 페이지 구현
- [ ] 평점 버튼 눌렀을 때 색깔이 채워지도록 구현
- [ ] 스크롤을 내릴 때 네비게이션바 중앙에 아이콘, 우측에 버튼 배치
